import { StreamChannel, WorldCupMatch, ChatMessage } from "./types";

export const CHANNELS: StreamChannel[] = [
  {
    id: "caze-tv-br",
    name: "Cazé TV BR (Main Stream HD)",
    url: "https://dfr80qz435crc.cloudfront.net/MNOP/Amagi/Caze/Caze_TV_BR/1080p-vtt/index.m3u8",
    description: "Cloudfront high-speed CDN streaming Cazé TV Brazil World Cup Coverage.",
    latency: 28,
    bitrate: "1080p @ 60fps",
    isHttps: true,
    category: "Main Broadcaster"
  },
  {
    id: "nyaler-23",
    name: "Server 2 (High Quality Feed)",
    url: "https://1nyaler.streamhostingcdn.top/stream/23/index.m3u8",
    description: "Alternative High Bandwidth server. Fast loading CDN mirror.",
    latency: 42,
    bitrate: "1080p",
    isHttps: true,
    category: "Server Alternates"
  },
  {
    id: "nyaler-32",
    name: "Server 3 (Alternate Stream)",
    url: "https://1nyaler.streamhostingcdn.top/stream/32/index.m3u8",
    description: "Backup stream server for high-load match peaks.",
    latency: 55,
    bitrate: "720p",
    isHttps: true,
    category: "Server Alternates"
  },
  {
    id: "ptv-sports",
    name: "PTV Sports World Cup Live",
    url: "https://tvsen5.aynaott.com/PtvSports/index.m3u8",
    description: "Live broadcasting feed directly from PTV Sports server.",
    latency: 89,
    bitrate: "1080p @ 30fps",
    isHttps: true,
    category: "Alternative Feeds"
  },
  {
    id: "mono-stream-http",
    name: "Server 1 (Mono Audio Feed)",
    url: "http://103.59.176.72:8083/live1/tracks-v1a1/mono.m3u8?token=123",
    description: "Direct IP HLS streaming server.",
    latency: 120,
    bitrate: "720p",
    isHttps: false,
    category: "Alternative Feeds"
  },
  {
    id: "raw-ts-feed",
    name: "Direct TV MPEG-TS Feed",
    url: "http://rgkkw.live/live/1Aoen7elp5/IgMJ60tmAa/130714.ts",
    description: "Direct TS packet stream link. Loaded as continuous transport stream.",
    latency: 180,
    bitrate: "Raw TS Stream",
    isHttps: false,
    category: "Alternative Feeds"
  }
];

export const WORLD_CUP_MATCHES: WorldCupMatch[] = [
  {
    id: "match-1",
    homeTeam: "Mexico",
    homeCode: "MEX",
    homeFlag: "🇲🇽",
    awayTeam: "South Africa",
    awayCode: "RSA",
    awayFlag: "🇿🇦",
    homeScore: 2,
    awayScore: 0,
    status: "FINISHED",
    time: "FT",
    group: "Group A",
    stadium: "Mexico City Stadium",
    stats: {
      possession: [58, 42],
      shotsOnTarget: [5, 2],
      shotsOffTarget: [7, 4],
      fouls: [11, 15],
      corners: [6, 2],
      yellowCards: [1, 3]
    }
  },
  {
    id: "match-2",
    homeTeam: "South Korea",
    homeCode: "KOR",
    homeFlag: "🇰🇷",
    awayTeam: "Czechia",
    awayCode: "CZE",
    awayFlag: "🇨🇿",
    homeScore: 2,
    awayScore: 1,
    status: "FINISHED",
    time: "FT",
    group: "Group A",
    stadium: "Guadalajara Stadium",
    stats: {
      possession: [51, 49],
      shotsOnTarget: [4, 4],
      shotsOffTarget: [9, 6],
      fouls: [12, 10],
      corners: [3, 5],
      yellowCards: [2, 1]
    }
  },
  {
    id: "match-3",
    homeTeam: "Canada",
    homeCode: "CAN",
    homeFlag: "🇨🇦",
    awayTeam: "Bosnia & Herzegovina",
    awayCode: "BIH",
    awayFlag: "🇧🇦",
    homeScore: 1,
    awayScore: 1,
    status: "FINISHED",
    time: "FT",
    group: "Group B",
    stadium: "Toronto Stadium",
    stats: {
      possession: [52, 48],
      shotsOnTarget: [3, 3],
      shotsOffTarget: [5, 5],
      fouls: [9, 11],
      corners: [4, 3],
      yellowCards: [1, 2]
    }
  },
  {
    id: "match-4",
    homeTeam: "USA",
    homeCode: "USA",
    homeFlag: "🇺🇸",
    awayTeam: "Paraguay",
    awayCode: "PAR",
    awayFlag: "🇵🇾",
    homeScore: 4,
    awayScore: 1,
    status: "FINISHED",
    time: "FT",
    group: "Group D",
    stadium: "Los Angeles Stadium",
    stats: {
      possession: [55, 45],
      shotsOnTarget: [8, 3],
      shotsOffTarget: [6, 5],
      fouls: [14, 16],
      corners: [7, 2],
      yellowCards: [2, 4]
    }
  },
  {
    id: "match-5",
    homeTeam: "Qatar",
    homeCode: "QAT",
    homeFlag: "🇶🇦",
    awayTeam: "Switzerland",
    awayCode: "SUI",
    awayFlag: "🇨🇭",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "1:00 AM BST",
    group: "Group B",
    stadium: "San Francisco Bay Area Stadium"
  },
  {
    id: "match-6",
    homeTeam: "Brazil",
    homeCode: "BRA",
    homeFlag: "🇧🇷",
    awayTeam: "Morocco",
    awayCode: "MAR",
    awayFlag: "🇲🇦",
    homeScore: 2,
    awayScore: 1,
    status: "LIVE",
    time: "62'",
    group: "Group C",
    stadium: "New York New Jersey Stadium",
    stats: {
      possession: [61, 39],
      shotsOnTarget: [6, 2],
      shotsOffTarget: [8, 4],
      fouls: [9, 14],
      corners: [5, 3],
      yellowCards: [1, 2]
    }
  },
  {
    id: "match-7",
    homeTeam: "Haiti",
    homeCode: "HAI",
    homeFlag: "🇭🇹",
    awayTeam: "Scotland",
    awayCode: "SCO",
    awayFlag: "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "7:00 AM BST",
    group: "Group C",
    stadium: "Boston Stadium"
  },
  {
    id: "match-8",
    homeTeam: "Australia",
    homeCode: "AUS",
    homeFlag: "🇦🇺",
    awayTeam: "Türkiye",
    awayCode: "TUR",
    awayFlag: "🇹🇷",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "10:00 AM BST",
    group: "Group D",
    stadium: "BC Place Vancouver"
  },
  {
    id: "match-9",
    homeTeam: "Germany",
    homeCode: "GER",
    homeFlag: "🇩🇪",
    awayTeam: "Curaçao",
    awayCode: "CUW",
    awayFlag: "🇨🇼",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "11:00 PM BST",
    group: "Group E",
    stadium: "Houston Stadium"
  },
  {
    id: "match-10",
    homeTeam: "Netherlands",
    homeCode: "NED",
    homeFlag: "🇳🇱",
    awayTeam: "Japan",
    awayCode: "JPN",
    awayFlag: "🇯🇵",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "2:00 AM BST",
    group: "Group F",
    stadium: "Dallas Stadium"
  },
  {
    id: "match-11",
    homeTeam: "Ivory Coast",
    homeCode: "CIV",
    homeFlag: "🇨🇮",
    awayTeam: "Ecuador",
    awayCode: "ECU",
    awayFlag: "🇪🇨",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "5:00 AM BST",
    group: "Group E",
    stadium: "Philadelphia Stadium"
  },
  {
    id: "match-12",
    homeTeam: "Sweden",
    homeCode: "SWE",
    homeFlag: "🇸🇪",
    awayTeam: "Tunisia",
    awayCode: "TUN",
    awayFlag: "🇹🇳",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "8:00 AM BST",
    group: "Group F",
    stadium: "Monterrey Stadium"
  },
  {
    id: "match-13",
    homeTeam: "Spain",
    homeCode: "ESP",
    homeFlag: "🇪🇸",
    awayTeam: "Cabo Verde",
    awayCode: "CPV",
    awayFlag: "🇨🇻",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "10:00 PM BST",
    group: "Group H",
    stadium: "Atlanta Stadium"
  },
  {
    id: "match-14",
    homeTeam: "Belgium",
    homeCode: "BEL",
    homeFlag: "🇧🇪",
    awayTeam: "Egypt",
    awayCode: "EGY",
    awayFlag: "🇪🇬",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "1:00 AM BST",
    group: "Group G",
    stadium: "Seattle Stadium"
  },
  {
    id: "match-15",
    homeTeam: "Saudi Arabia",
    homeCode: "KSA",
    homeFlag: "🇸🇦",
    awayTeam: "Uruguay",
    awayCode: "URU",
    awayFlag: "🇺🇾",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "4:00 AM BST",
    group: "Group H",
    stadium: "Miami Stadium"
  },
  {
    id: "match-16",
    homeTeam: "Iran",
    homeCode: "IRN",
    homeFlag: "🇮🇷",
    awayTeam: "New Zealand",
    awayCode: "NZL",
    awayFlag: "🇳🇿",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "7:00 AM BST",
    group: "Group G",
    stadium: "Los Angeles Stadium"
  },
  {
    id: "match-17",
    homeTeam: "France",
    homeCode: "FRA",
    homeFlag: "🇫🇷",
    awayTeam: "Senegal",
    awayCode: "SEN",
    awayFlag: "🇸🇳",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "1:00 AM BST",
    group: "Group I",
    stadium: "New York New Jersey Stadium"
  },
  {
    id: "match-18",
    homeTeam: "Iraq",
    homeCode: "IRQ",
    homeFlag: "🇮🇶",
    awayTeam: "Norway",
    awayCode: "NOR",
    awayFlag: "🇳🇴",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "4:00 AM BST",
    group: "Group I",
    stadium: "Boston Stadium"
  },
  {
    id: "match-19",
    homeTeam: "Argentina",
    homeCode: "ARG",
    homeFlag: "🇦🇷",
    awayTeam: "Algeria",
    awayCode: "ALG",
    awayFlag: "🇩🇿",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "7:00 AM BST",
    group: "Group J",
    stadium: "Kansas City Stadium"
  },
  {
    id: "match-20",
    homeTeam: "England",
    homeCode: "ENG",
    homeFlag: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    awayTeam: "Croatia",
    awayCode: "CRO",
    awayFlag: "🇭🇷",
    homeScore: 0,
    awayScore: 0,
    status: "UPCOMING",
    time: "8:00 PM BST",
    group: "Group L",
    stadium: "Dallas Stadium"
  }
];

export const INITIAL_CHAT: ChatMessage[] = [
  {
    id: "m-1",
    username: "NeymarFan_10",
    text: "BRAZIL IS COOKING! What a pass from Vinicius! 🇧🇷🔥🔥",
    time: "12:41",
    avatarColor: "bg-green-500"
  },
  {
    id: "m-2",
    username: "MbappeSpeedster",
    text: "Don't count France out yet, Mbappe is about to turn on the turbos! ⚡️🇫🇷",
    time: "12:42",
    avatarColor: "bg-blue-500"
  },
  {
    id: "m-3",
    username: "SystemBroadcast",
    text: "Goal Alert! Brazil 2 - 1 France (Neymar Jr. Pen 68')",
    time: "12:43",
    avatarColor: "bg-amber-600",
    isSystem: true
  },
  {
    id: "m-4",
    username: "RefereeRef",
    text: "Yellow card to Upamecano for that tackle. Completely justified.",
    time: "12:43",
    avatarColor: "bg-yellow-500",
    isModerator: true
  },
  {
    id: "m-5",
    username: "MessiGoat10",
    text: "Waiting for the Argentina England game to heat up! Leo is starting today!",
    time: "12:44",
    avatarColor: "bg-cyan-500"
  }
];
